from enum import Enum, auto


class EventType(Enum):
    CUSTOMER_PLACED_ORDER = auto()
    ESTABLISHMENT_ACCEPTED_ORDER = auto()
    ESTIMATED_ORDER_PREPARATION_TIME = auto()
    ESTABLISHMENT_REJECTED_ORDER = auto()
    ESTABLISHMENT_PREPARING_ORDER = auto()
    ESTABLISHMENT_FINISHED_ORDER = auto()
    DRIVER_ACCEPTED_DELIVERY = auto()
    DRIVER_REJECTED_DELIVERY = auto()
    DRIVER_PICKING_UP_ORDER = auto()
    DRIVER_PICKED_UP_ORDER = auto()
    DRIVER_DELIVERING_ORDER = auto()
    DRIVER_ARRIVED_DELIVERY_LOCATION = auto()
    CUSTOMER_RECEIVED_ORDER = auto()
    DRIVER_DELIVERED_ORDER = auto()
    DRIVER_ACCEPTED_ROUTE = auto()
    DRIVER_ACCEPTED_EXTENSION_ROUTE = auto()
    DRIVER_REJECTED_ROUTE = auto()
    OPTMIZER_REJECTED_DELIVERY = auto()
    TIME_FOR_AGENT_ALLOCATE_DRIVER = auto()
